language: java
sudo: false # faster builds

matrix:
  include:
  - os: linux
    jdk: oraclejdk8
#  - os: osx
#    osx_image: xcode8
install: mvn clean install -DskipTests=true -B -V
script:
- mvn test -P fast -DargLine="-DACCOUNT_HOST=$ACCOUNT_HOST -DACCOUNT_KEY=$ACCOUNT_KEY" cobertura:cobertura
after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
  - $HOME/.m2
