language: java
sudo: false # faster builds

matrix:
  include:
  - os: linux
    jdk: openjdk8
script:
- mvn dependency:resolve
- mvn package
after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
  - $HOME/.m2
